# Generated by Django 4.2 on 2023-04-29 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email_address", models.TextField()),
                ("date_of_birth", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_categories", models.TextField()),
                ("user_video_history", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoDetails",
            fields=[
                ("user_name", models.TextField()),
                ("video_id", models.IntegerField(primary_key=True, serialize=False)),
                ("video_title", models.TextField(max_length=200)),
                ("video_duration", models.IntegerField()),
                ("video_views", models.IntegerField()),
                ("video_likes", models.IntegerField()),
                ("video_dislikes", models.IntegerField()),
                ("video_category", models.TextField(max_length=100)),
            ],
        ),
    ]
